# Generated by Django 3.2.9 on 2021-12-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_cropmodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Idafarmuser',
            new_name='Farmusers',
        ),
    ]
